DROP DATABASE Empresa; -- APAGAR BASE DE DADOS
CREATE DATABASE Empresa; -- CRIAR BASE DE DADOS

USE Empresa; -- ACESSAR BASE DE DADOS

-- CRIAR TABELA FUNCIONARIO
CREATE TABLE Funcionario(
	Codigo INT PRIMARY KEY,
	Nome NVARCHAR(100), -- O VARCHAR SEM N NAO PERMITE CARACTERES ESPECIAIS
	);

-- INSERIR VALORES EM TABELAS
INSERT INTO Funcionario(Codigo, Nome)
VALUES
(1, 'Isaque'),
(2, 'Xerofoscremildo')
-- OU
INSERT INTO Funcionario VALUES
(3, 'Jurexcrivaldino')

-- LISTAR DADOS INSERIDOS
SELECT * FROM Funcionario;

-- LISTAR IDS E NOMES DOS FUNCIONARIOS
SELECT Codigo, Nome FROM Funcionario;

-- LISTAR FUNCIONARIOS COM ID >2
SELECT * FROM Funcionario WHERE Codigo > 2;

-- LISTAR FUNCIONARIOS QUE COMECEM COM A LETRA I
SELECT * FROM Funcionario WHERE Nome LIKE 'I%';

-- LISTAR FUNCIONARIOS QUE TERMINEM COM A LETRA O
SELECT * FROM Funcionario WHERE Nome LIKE '%o';

-- ORDENAR VALORES
-- EM ORDEM DECRESCENTE
SELECT * FROM Funcionario
ORDER BY Codigo DESC;

-- EM ORDEM ALFABETICA
SELECT * FROM Funcionario
ORDER BY Nome ASC;

-- ATUALIZACAO DE DADOS
UPDATE Funcionario SET Nome = 'Isaque Silva'
WHERE Nome = 'Isaque'; -- SEM WHERE, MANIPULA TODA A TABELA

-- EXCLUSAO DE DADOS
DELETE FROM Funcionario
WHERE Codigo = 1;